Add MACE aggregation model
Toloka/crowd-kit pull request #32
Opened 2022-07-19 09:51 UTC by pilot7747

I have added the MACE aggregation model.
https://www.cs.cmu.edu/~hovy/papers/13HLT-MACE.pdf

## Description
Based on the original VB inference implementation, I wrote it in Python.

### Connected issues (if any)
https://github.com/Toloka/crowd-kit/issues/5

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation and examples improvement (changes affected documentation and/or examples)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-07-21 12:32 UTC, dustalov requested changes
All good. Have you tried running benchmarks from Hovy et al.? Does our code produce comparable results?

2022-07-21 13:21 UTC, dustalov commented
Also, please add an entry to `README.md`.

2022-07-22 09:16 UTC, pilot7747 commented
@dustalov It would be great, but I wasn't able to find the original datasets because they are not available. Seems like links to ai.stanford.com have expired. However, I did compared it with the Java implementation and checked if it returns the same numbers at every step on example datasets.

2022-07-22 12:13 UTC, pilot7747 commented on tests/aggregation/test_mace_aggregation.py
> +        toy_ground_truth_df: pd.DataFrame
Done

2022-07-22 12:13 UTC, dustalov approved these changes

2022-07-22 12:14 UTC, merged