Kos implementation
Toloka/crowd-kit pull request #35
Opened 2022-07-24 14:47 UTC by aliskin

I added an implementation of KOS algorithm.

## Description
This commit includes implementation of KOS algorithm along with a few basic tests. Let me know if I need to make more tests.
The implementation was tested on the two datasets from [this paper](http://i.cs.hku.hk/~ydzheng2/crowd_truth_inference/crowd_truth_infer.pdf) and it achieves almost the same F1 and accuracy but works much faster.

I noticed that other aggregation algorithms have a parameter tol – should I add it to this method too?
Another question is about normalization. On each iteration the absolute values of intermediate grow and when there are many iterations the intermediate values might become nan. Any ideas on that point a very appreciated. Thanks! 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation and examples improvement (changes affected documentation and/or examples)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-07-25 09:56 UTC, dustalov requested changes

2022-07-25 09:56 UTC, dustalov commented on crowdkit/aggregation/classification/kos.py
> +
Please define all the attributes here, including the ones like `labels_` that we write in `fit()` and other methods. `MajorityVote` might be a good example.

2022-07-25 09:56 UTC, dustalov commented on tests/aggregation/test_kos_aggregation.py
> +def test_aggregate_kos_on_data_with_bool_labels(n_iter, data_with_bool_labels, bool_labels_ground_truth):
Please add type annotations everywhere.

2022-07-25 09:56 UTC, dustalov commented on crowdkit/aggregation/classification/kos.py
> +            self.labels_ = pd.Series(dtype=float)
It seems that we do the same thing in `DawidSkene`, but I believe that was a typo.

2022-07-25 09:57 UTC, dustalov commented
And also please address the merge conflict.

2022-07-27 14:07 UTC, aliskin commented on crowdkit/aggregation/classification/kos.py
> +    def fit_predict(self, data: pd.DataFrame) -> pd.DataFrame:
Yes, I think we can think of them as logits. The meaning is that the bigger values come from more reliable workers according to our belief.

2022-07-27 19:32 UTC, dustalov commented on crowdkit/aggregation/classification/kos.py
> +    def fit_predict(self, data: pd.DataFrame) -> pd.DataFrame:
Does it affect the code?

2022-07-28 06:32 UTC, pilot7747 commented on crowdkit/aggregation/classification/kos.py
> +    def fit_predict(self, data: pd.DataFrame) -> pd.DataFrame:
I don't see `fit_predict_proba` method, maybe we can just return softmax?

2022-07-28 08:48 UTC, dustalov commented on crowdkit/aggregation/classification/kos.py
> +    def fit_predict(self, data: pd.DataFrame) -> pd.DataFrame:
These numbers are not used as logits in the method. I propose not doing this now, however the change does not look difficult.

2022-07-28 08:54 UTC, dustalov approved these changes

2022-07-28 08:56 UTC, merged