Add files via upload
Toloka/crowd-kit pull request #72
Opened 2023-03-31 17:04 UTC by Senarect

## Checklist

- [x ] I have read the **CONTRIBUTING** document
- [x ] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2023-04-04 13:39 UTC, pilot7747 requested changes

2023-04-04 13:39 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "Welcome to this tutorial! Have you done with the image segmentation  with crowdsourcing and now you need to somehow get the final results? Find out how to aggregate the data with methods fro
I've added a couple of comments for Text Aggregation example PR. Please fix ones that apply here too.

2023-04-07 14:53 UTC, pilot7747 requested changes

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "df.columns"
why not `df.head()`?

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "result_EM = SegmentationEM().fit_predict(df)"
`result_EM` -> `result_em`

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "  IOU_EM = np.append(IOU_EM, overlap.sum()/float(union.sum()))\n",
`overlap.sum()/float(union.sum())` -> `overlap.sum() / float(union.sum())`

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "for i in range(0, len(result_MajorityVote)-1):\n",
`len(result_MajorityVote)-1` -> `len(result_MajorityVote) - 1`

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "  overlap = result_MajorityVote[i]*gt[i] \n",
`result_MajorityVote[i]*gt[i]` -> `result_MajorityVote[i] * gt[i]`

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "IOU_EM.mean()"
`IOU_EM` -> `iou_em`

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "  IOU_MajorityVote = np.append(IOU_MajorityVote, overlap.sum()/float(union.sum()))\n",
`IOU_MajorityVote` -> `iou_majority_vote`

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "  IOU_MajorityVote = np.append(IOU_MajorityVote, overlap.sum()/float(union.sum()))\n",
`overlap.sum()/float(union.sum())` -> `overlap.sum() / float(union.sum())`

2023-04-07 14:53 UTC, pilot7747 commented on examples/Image-Segmentation.ipynb
> +        "See? All the results are quite good but the SegmentationEM shows slightly better result.\n",
`See?`. Please be less passive-aggressive

2023-04-13 12:55 UTC, pilot7747 approved these changes

2023-04-13 13:39 UTC, Senarect commented on examples/Image-Segmentation.ipynb
> +        "# How to Aggregate Image-Segmentation tasks via Crowdsourcing"
I do not undestand :c

2023-04-13 15:37 UTC, Senarect commented on examples/Image-Segmentation.ipynb
> +        "# How to Aggregate Image-Segmentation tasks via Crowdsourcing"
No :c
There aren't any pictures in the dataset, only their masks

2023-04-21 11:47 UTC, merged