Documentation updates for Multilabel and Pairwise documentation
Toloka/crowd-kit pull request #79
Opened 2023-08-16 11:38 UTC by Natalyl3

Updated the Multilabel and Pairwise sections:

- added extra information to the models descriptions;
- added descriptions for parameters;
- fixed errors and typos in descriptions.

2023-08-22 11:10 UTC, pilot7747 requested changes

2023-08-22 11:10 UTC, pilot7747 commented on crowdkit/aggregation/pairwise/bradley_terry.py
> +    where $w_{ij}$ denotes the number of times individual $i$ has beaten individual $j$ and we assume $w_{ij} = 0$ by convention.
Not an "individual", I suppose it's better to say "object" here. Also, don't understand why does w_ij equals zero.

2023-08-28 07:35 UTC, denaxen commented on crowdkit/aggregation/multilabel/binary_relevance.py
> +    D_j = {(x^i, y_j^i) | 1 <= i <= m}.
Please check i and j meanings; now I guess "1 <= j <= m" is correct since we have j class labels (this follows from "for each class label $λ_j$")

2023-08-28 07:39 UTC, denaxen commented on crowdkit/aggregation/multilabel/binary_relevance.py
> +    D_j = {(x^i, y_j^i) | 1 <= i <= m}.
Please add the meaning of the m parameter and a brief explanation of `y_j^i`

2023-08-28 07:45 UTC, denaxen requested changes

2023-08-28 07:45 UTC, denaxen commented on crowdkit/aggregation/multilabel/binary_relevance.py
> +    D_j = {(x^i, y_j^i) | 1 <= i <= m}.
Please add the meaning of the m parameter and a brief explanation of `y_j^i`

2023-08-29 06:18 UTC, Natalyl3 commented
@pilot7747, @denaxen Please check my fixes

2024-02-03 20:08 UTC, closed without merging

2024-02-03 20:08 UTC, dustalov commented
I recommend revising and resubmitting this pull request due to the large difference with the upstream.